// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxxdhTVvKXVhMqGl-wX4rtPoqDIGG2HJw',
    appId: '1:611961244690:web:3918fa55bb6bb241c2dccb',
    messagingSenderId: '611961244690',
    projectId: 'tdp028-16071',
    authDomain: 'tdp028-16071.firebaseapp.com',
    storageBucket: 'tdp028-16071.firebasestorage.app',
    measurementId: 'G-8R9QP749JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ8ZGHRA9U7RUyaa0VqW3eyzi0PAEepXk',
    appId: '1:611961244690:android:b9981f8e208720e6c2dccb',
    messagingSenderId: '611961244690',
    projectId: 'tdp028-16071',
    storageBucket: 'tdp028-16071.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiCVsvCGDaqfMLJFRx2hpUsEEeLaA6Uzg',
    appId: '1:611961244690:ios:73cd8ac7ebfb81a3c2dccb',
    messagingSenderId: '611961244690',
    projectId: 'tdp028-16071',
    storageBucket: 'tdp028-16071.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiCVsvCGDaqfMLJFRx2hpUsEEeLaA6Uzg',
    appId: '1:611961244690:ios:73cd8ac7ebfb81a3c2dccb',
    messagingSenderId: '611961244690',
    projectId: 'tdp028-16071',
    storageBucket: 'tdp028-16071.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxxdhTVvKXVhMqGl-wX4rtPoqDIGG2HJw',
    appId: '1:611961244690:web:e9beb2dc8c15338dc2dccb',
    messagingSenderId: '611961244690',
    projectId: 'tdp028-16071',
    authDomain: 'tdp028-16071.firebaseapp.com',
    storageBucket: 'tdp028-16071.firebasestorage.app',
    measurementId: 'G-B98B51VKPQ',
  );
}
